language: python
branches:
  only:
  - master
matrix:
  include:
    - name: Linux 64-bit
      sudo: required
      services:
        - docker
      env:
        - CIBW_SKIP=*manylinux1_i686*
        - CIBW_BUILD:cp3?-*
    - name: macOS
      os: osx
      language: generic
      env:
        - CIBW_BUILD:cp3?-*
env:
  global:
    - TWINE_USERNAME=hledoux
    # Note: TWINE_PASSWORD is set in Travis settings.
script:
  - echo $TWINE_USERNAME
  - "pip install cibuildwheel==0.10.2 setuptools-rust==0.10.3"
  - export RUST_BACKTRACE=1
  - export CIBW_BEFORE_BUILD="pip install setuptools-rust==0.10.3 && source ./travis/travis"
  - export CIBW_SKIP=cp34-*\ $CIBW_SKIP
  - export CIBW_ENVIRONMENT="CI=\"$CI\" TRAVIS_BRANCH=\"$TRAVIS_BRANCH\" TRAVIS_COMMIT=\"$TRAVIS_COMMIT\" PATH=\"\$HOME/.cargo/bin:\$PATH\""
  - export CIBW_TEST_COMMAND="python -c 'import startin'"
  - cibuildwheel --output-dir wheelhouse
  - export TWINE_PASSWORD=$TWINE_PASSWORD
  - python -m pip install twine
  - python -m twine upload wheelhouse/*.whl --verbose
