name: Build sphinx docs + gh-pages

on:
  # push:
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    # - name: Install GDAL
    #   run: |
    #     sudo add-apt-repository -y ppa:ubuntugis/ppa
    #     sudo apt update
    #     sudo apt install libgdal-dev gdal-bin 
    #     pip install sphinx-multiversion
    #     pip install sphinx-celery
    
    - uses: actions/setup-python@v2        
    
    - uses: actions/checkout@v2

    - uses: syphar/restore-virtualenv@v1
      id: myvenv
      with:
        requirement_files: requirements.txt  

    - name: Install sphinx theme
      run: |
        pip install sphinx-celery    
    
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        manylinux: auto
        command: develop
    - name: Running the Sphinx to gh-pages Action
      uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0.0
      with:
        branch: master
        dir_docs: docs
        sphinxapiopts: '-b html'       


